### ISSUE TITLE
 checkpoint file URL is not available

### ISSUE THREAD

**Issue by TjFish** [IST-DASLab/ACDC#2]
Hello, great work!
It seems the checkpoint URL is no longer available.
can you please help me? Thank you very much！

**Comment by ohaijen** [comment]
Hi TJFish,

Thanks for the kind words! Unfortunately our institute has been hit by a cyberattack, and our services are offline for the next week or two. I can let you know when everything is backed up, or, if you need a couple of checkpoints now, we can send them to you. 

Best, Jen

**Comment by TjFish** [comment]
Thank you very much for your reply.
I would appreciate it if you would send the checkpoint file to the following email address.
 ouyangbridge@gmail.com
Thanks again!

**Comment by TjFish** [comment]
> if you need a couple of checkpoints now

ResNet50 95%
ResNet50 98%
ResNet50 95% 2x
MobileNetV1 90%

We currently only need the 4 checkpoints above. If you have time, please send them to my email address, [ouyangbridge@gmail.com](mailto:ouyangbridge@gmail.com) thank you very much!
